maintainer        "Heavy Water Software Inc."
maintainer_email  "darrin@heavywater.ca"
license           "Apache 2.0"
description       "Installs Percona client and server"
version           "0.1.1"
supports          "ubuntu"
